### ISSUE TITLE
Sink connector stops sending alerts to slack & discord, Need a way to troubleshoot

### ISSUE THREAD

**Issue by ajhunyady** [infinyon/http-sink-connector#29]
The connector reads from a topic with the following data:

```
{"forks":137,"stars":1763}
{"forks":137,"stars":1763}
{"forks":137,"stars":1763}
{"forks":138,"stars":1763}
{"forks":138,"stars":1763}
{"forks":138,"stars":1764}
{"forks":138,"stars":1764}
{"forks":138,"stars":1764}
```

I am using the following sink connector:

```
meta:
  version: 0.1.0
  name: discord-stars-sink
  type: http-sink
  topic: github-stars
http:
  endpoint: "https://discord.com/api/webhooks/<key>"
  headers:
    - "Content-Type: application/json"
transforms:
  - uses: infinyon-labs/stars-forks-changes@0.1.0
  - uses: infinyon/jolt@0.1.0
    with:
      spec:
        - operation: shift
          spec:
            "result": "content"
```

The connector stopped sending stars to slack. I have a 2nd connector sending stars to discord, and this is failing too.

I need a way to troubleshoot this issue, and prevent it from reoccurring. 

Note: This is an issue in my production environment, and it needs immediate attention.
